from config import app
from routes import (
    whois_search,
    nmap_scan,
    view_history,
    view_users,
    delete_user,
    edit_user,
    home,
    register,
    login,
    logout,
    clearcheck,
    ipcheck,
    security_vulnerabilities,
    penetration_tools,
    load_user,
    virustotal_url,
    virustotal_url_result,
)
